# Generated by Django 6.0.1 on 2026-01-26 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
