# Generated by Django 6.0.1 on 2026-01-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='goal',
        ),
    ]
