# Generated by Django 6.0.1 on 2026-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaign_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='goals',
            field=models.JSONField(blank=True, default=list, help_text='Campaign goals as JSON array'),
        ),
    ]
